# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: elizadave6@gmail.com
author_name: elizabeth-agada
preset_name: starter
project_name: liz-crowdfunding-frontend

